# Generated by Django 5.0.1 on 2024-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "flight_type",
                    models.CharField(
                        choices=[
                            ("Nacional", "Nacional"),
                            ("Internacional", "Internacional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.IntegerField()),
            ],
        ),
    ]
